version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-poc
    ports:
      - "5672:5672"     # AMQP para apps
      - "15672:15672"   # UI web
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
