spring:
  application:
    name: demo.rabbit
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/polizas_db
    username: postgres
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit

server:
  port: ${PORT:8081}
